#spring:
#  datasource:
#    server.port = 8088
#    spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
#    spring.datasource.username=project
#    spring.datasource.password=project
#    spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#hikari:
#  maximum-pool-size: 20
#  jpa:
#    hibernate:
#    ddl-auto: update
#    show-sql: true